@url = http://localhost:8080/api/agent

GET {{url}} HTTP/1.1

###

GET {{url}}/2 HTTP/1.1

###

POST {{url}} HTTP/1.1
Content-Type: application/json

{
    "firstName": "Arnold",
    "middleName": "G",
    "lastName": "Zeus",
    "dob": "1965-06-05",
    "heightInInches": 65,
    "agencies": [],
    "aliases": []
}

###

PUT {{url}}/2 HTTP/1.1
Content-Type: application/json

{
    "agentId": 2,
    "firstName": "Claudian",
    "middleName": "C",
    "lastName": "O'Lynn",
    "dob": "1956-11-09",
    "heightInInches": 41,
    "agencies": [],
    "aliases": []
}

###

DELETE {{url}}/6 HTTP/1.1