// Mission Tests

// Getting all Missions
GET http://localhost:8080/api/mission HTTP/1.1

###

// Getting one Mission
GET http://localhost:8080/api/mission/6 HTTP/1.1

###

// Getting another Mission
GET http://localhost:8080/api/mission/2 HTTP/1.1

###

// Adding a Mission
POST http://localhost:8080/api/mission HTTP/1.1
Content-Type: application/json

{
    "codeName": "Blackhawhk",
    "notes": "None",
    "startDate": "03/04/1924",
    "projectedEndDate": "04/16/1924",
    "actualEndDate": "06/08/1924",
    "operationalCost": 500,
    "agencyId": 1
}

###

// Updating one Mission
PUT http://localhost:8080/api/mission/2 HTTP/1.1
Content-Type: application/json

{
    "codeName": "Blackhawhk",
    "notes": "None",
    "startDate": "03/04/1924",
    "projectedEndDate": "04/16/1924",
    "actualEndDate": "06/08/1924",
    "operationalCost": 500,
    "agencyId": 1
}

###

// Removing a Mission
DELETE http://localhost:8080/api/mission/9 HTTP/1.1