# Send a pet to each method as JSON in the request body.
POST /pets HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "name": "Gibby",
    "type": "Cat"
}

###

PUT /pets/9 HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "petId": 9,
    "name": "Midge",
    "type": "Pug"
}